# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(467, 391)
        MainWindow.setMinimumSize(QtCore.QSize(467, 391))
        MainWindow.setMaximumSize(QtCore.QSize(467, 391))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Style/Stylesheet/icons8-ethernet-on-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 431, 281))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_line = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_line.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.input_line.setFrame(True)
        self.input_line.setReadOnly(False)
        self.input_line.setObjectName("input_line")
        self.horizontalLayout.addWidget(self.input_line)
        self.go_button = QtWidgets.QPushButton(self.layoutWidget)
        self.go_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(85, 255, 255);\n"
"color: rgb(0, 0, 0);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Style/Stylesheet/icons8-web-address-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.go_button.setIcon(icon1)
        self.go_button.setObjectName("go_button")
        self.horizontalLayout.addWidget(self.go_button)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color: rgb(37, 255, 26);\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.ip_address = QtWidgets.QLineEdit(self.layoutWidget)
        self.ip_address.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.ip_address.setText("")
        self.ip_address.setFrame(True)
        self.ip_address.setReadOnly(True)
        self.ip_address.setObjectName("ip_address")
        self.verticalLayout.addWidget(self.ip_address)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("color: rgb(37, 255, 26);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.country = QtWidgets.QLineEdit(self.layoutWidget)
        self.country.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.country.setFrame(True)
        self.country.setReadOnly(True)
        self.country.setObjectName("country")
        self.verticalLayout_2.addWidget(self.country)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setStyleSheet("color: rgb(37, 255, 26);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.region = QtWidgets.QLineEdit(self.layoutWidget)
        self.region.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.region.setFrame(True)
        self.region.setReadOnly(True)
        self.region.setObjectName("region")
        self.verticalLayout_3.addWidget(self.region)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setStyleSheet("color: rgb(37, 255, 26);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.longitude = QtWidgets.QLineEdit(self.layoutWidget)
        self.longitude.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.longitude.setFrame(True)
        self.longitude.setReadOnly(True)
        self.longitude.setObjectName("longitude")
        self.verticalLayout_4.addWidget(self.longitude)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setStyleSheet("color: rgb(37, 255, 26);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.latitude = QtWidgets.QLineEdit(self.layoutWidget)
        self.latitude.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.latitude.setFrame(True)
        self.latitude.setReadOnly(True)
        self.latitude.setObjectName("latitude")
        self.verticalLayout_5.addWidget(self.latitude)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setStyleSheet("color: rgb(37, 255, 26);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.isp = QtWidgets.QLineEdit(self.layoutWidget)
        self.isp.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.isp.setFrame(True)
        self.isp.setReadOnly(True)
        self.isp.setObjectName("isp")
        self.verticalLayout_6.addWidget(self.isp)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 350, 85, 18))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.status = QtWidgets.QLabel(self.layoutWidget1)
        self.status.setStyleSheet("color: rgb(37, 255, 26);")
        self.status.setObjectName("status")
        self.horizontalLayout_4.addWidget(self.status)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WhoDis"))
        self.input_line.setPlaceholderText(_translate("MainWindow", "Enter ip address / Domain name"))
        self.go_button.setText(_translate("MainWindow", "Go"))
        self.label.setText(_translate("MainWindow", "IP address / Domain name:"))
        self.label_2.setText(_translate("MainWindow", "Country:"))
        self.label_4.setText(_translate("MainWindow", "Region:"))
        self.label_5.setText(_translate("MainWindow", "Longitude:"))
        self.label_6.setText(_translate("MainWindow", "Latitude:"))
        self.label_7.setText(_translate("MainWindow", "ISP:"))
        self.label_8.setText(_translate("MainWindow", "Status:"))
        self.status.setText(_translate("MainWindow", "Ready"))
import resoucres_rc
