# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(467, 460)
        MainWindow.setMinimumSize(QtCore.QSize(467, 460))
        MainWindow.setMaximumSize(QtCore.QSize(467, 460))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Style/Stylesheet/icons8-ethernet-on-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QLineEdit{\n"
"\n"
"border: 1px;\n"
"border-radius:5px;\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(23, 230, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.longitude = QtWidgets.QLineEdit(self.centralwidget)
        self.longitude.setGeometry(QtCore.QRect(23, 255, 202, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.longitude.setFont(font)
        self.longitude.setStyleSheet("")
        self.longitude.setFrame(True)
        self.longitude.setReadOnly(True)
        self.longitude.setObjectName("longitude")
        self.ip_address = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_address.setGeometry(QtCore.QRect(22, 100, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.ip_address.setFont(font)
        self.ip_address.setStyleSheet("")
        self.ip_address.setText("")
        self.ip_address.setFrame(True)
        self.ip_address.setReadOnly(True)
        self.ip_address.setObjectName("ip_address")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(22, 75, 178, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(23, 150, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.country = QtWidgets.QLineEdit(self.centralwidget)
        self.country.setGeometry(QtCore.QRect(23, 175, 205, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.country.setFont(font)
        self.country.setStyleSheet("")
        self.country.setFrame(True)
        self.country.setReadOnly(True)
        self.country.setObjectName("country")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 150, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.region = QtWidgets.QLineEdit(self.centralwidget)
        self.region.setGeometry(QtCore.QRect(246, 175, 205, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.region.setFont(font)
        self.region.setStyleSheet("")
        self.region.setFrame(True)
        self.region.setReadOnly(True)
        self.region.setObjectName("region")
        self.input_line = QtWidgets.QLineEdit(self.centralwidget)
        self.input_line.setGeometry(QtCore.QRect(20, 20, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.input_line.setFont(font)
        self.input_line.setStyleSheet("")
        self.input_line.setFrame(True)
        self.input_line.setReadOnly(False)
        self.input_line.setObjectName("input_line")
        self.go_button = QtWidgets.QPushButton(self.centralwidget)
        self.go_button.setGeometry(QtCore.QRect(320, 20, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.go_button.setFont(font)
        self.go_button.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(33, 150, 243);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(2, 136, 209);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(33, 33, 33);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Style/Stylesheet/icons8-web-address-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.go_button.setIcon(icon1)
        self.go_button.setObjectName("go_button")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(250, 230, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.latitude = QtWidgets.QLineEdit(self.centralwidget)
        self.latitude.setGeometry(QtCore.QRect(250, 255, 202, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.latitude.setFont(font)
        self.latitude.setStyleSheet("")
        self.latitude.setFrame(True)
        self.latitude.setReadOnly(True)
        self.latitude.setObjectName("latitude")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(22, 307, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.isp = QtWidgets.QLineEdit(self.centralwidget)
        self.isp.setGeometry(QtCore.QRect(22, 330, 431, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.isp.sizePolicy().hasHeightForWidth())
        self.isp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.isp.setFont(font)
        self.isp.setStyleSheet("")
        self.isp.setFrame(True)
        self.isp.setReadOnly(True)
        self.isp.setObjectName("isp")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(69, 390, 141, 16))
        self.status.setStyleSheet("")
        self.status.setObjectName("status")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(21, 390, 41, 16))
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 467, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuExit = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.menuExit.setFont(font)
        self.menuExit.setObjectName("menuExit")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menuBar)
        self.actionImport_List = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Style/ic_format_list_bulleted_128_28351.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImport_List.setIcon(icon2)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.actionImport_List.setFont(font)
        self.actionImport_List.setObjectName("actionImport_List")
        self.actionExport = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Style/export_icon-icons.com_52383.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport.setIcon(icon3)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.actionExport.setFont(font)
        self.actionExport.setObjectName("actionExport")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Style/ic_clear_128_28306.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")
        self.actionGithub = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Style/Github_icon-icons.com_49946.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGithub.setIcon(icon5)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.actionGithub.setFont(font)
        self.actionGithub.setObjectName("actionGithub")
        self.actionDonate = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Style/gift.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDonate.setIcon(icon6)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.actionDonate.setFont(font)
        self.actionDonate.setObjectName("actionDonate")
        self.actionWebsite = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Style/wondicon-ui-free-website_111210.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWebsite.setIcon(icon7)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.actionWebsite.setFont(font)
        self.actionWebsite.setObjectName("actionWebsite")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Style/about_3697.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon8)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName("actionAbout")
        self.menuExit.addAction(self.actionImport_List)
        self.menuExit.addAction(self.actionExport)
        self.menuExit.addSeparator()
        self.menuExit.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionGithub)
        self.menuAbout.addAction(self.actionDonate)
        self.menuAbout.addAction(self.actionWebsite)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuExit.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WhoDis"))
        self.label_5.setText(_translate("MainWindow", "Longitude:"))
        self.label.setText(_translate("MainWindow", "IP address / Domain name:"))
        self.label_2.setText(_translate("MainWindow", "Country:"))
        self.label_4.setText(_translate("MainWindow", "Region:"))
        self.input_line.setPlaceholderText(_translate("MainWindow", "Enter ip address / Domain name"))
        self.go_button.setText(_translate("MainWindow", "Go / Get IP"))
        self.label_6.setText(_translate("MainWindow", "Latitude:"))
        self.label_7.setText(_translate("MainWindow", "ISP:"))
        self.status.setText(_translate("MainWindow", "Ready"))
        self.label_8.setText(_translate("MainWindow", "Status:"))
        self.menuExit.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionImport_List.setText(_translate("MainWindow", "Import List"))
        self.actionImport_List.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionExport.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Esc"))
        self.actionGithub.setText(_translate("MainWindow", "Github"))
        self.actionDonate.setText(_translate("MainWindow", "Donate"))
        self.actionWebsite.setText(_translate("MainWindow", "Website"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
import resoucres_rc
